<link rel='manifest' href='/media/pwa/manifest.json'>

<link rel="apple-touch-icon" sizes="192x192" href="/media/pwa/images/icon-192x192.png"  />
<link rel="apple-touch-icon" sizes="32x32" href="/media/pwa/images/icon-32x32.png" />
<link rel="apple-touch-icon" sizes="512x512" href="/media/pwa/images/icon-512x512.png" />

<meta name="apple-mobile-web-app-title" content="Magento PWA" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="default" />
<meta name="theme-color" content="#b5121b" />
